"""Build ``ml/data/seed/car_models.csv`` from curated lists.

The data lives inline as Python tuples ``(make_normalized, model_name, segment, body_type)``.
We resolve ``make_id`` through ``car_makes.csv`` and compute ``name_normalized`` from
``model_name`` so they stay consistent.

Run:
    python ml/pipelines/_car_models_build.py
"""

from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MAKES_CSV = REPO / "ml" / "data" / "seed" / "car_makes.csv"
OUT_CSV = REPO / "ml" / "data" / "seed" / "car_models.csv"

# (make_normalized, model_name, segment, body_type)
DATA: list[tuple[str, str, str, str]] = [
    # ── russian (~25) ───────────────────────────────────────────
    ("lada", "Granta", "B", "sedan"),
    ("lada", "Vesta", "B", "sedan"),
    ("lada", "Niva Legend", "J_SUV", "suv"),
    ("lada", "Niva Travel", "J_CROSS", "crossover"),
    ("lada", "Largus", "M_MPV", "mpv"),
    ("lada", "Iskra", "B", "sedan"),
    ("lada", "X-Ray", "J_CROSS", "crossover"),
    ("lada", "Priora", "C", "sedan"),
    ("lada", "Kalina", "B", "hatchback"),
    ("lada", "Aura", "B", "sedan"),
    ("uaz", "Patriot", "J_SUV", "suv"),
    ("uaz", "Hunter", "J_SUV", "suv"),
    ("uaz", "Profi", "LCV", "pickup"),
    ("uaz", "3909", "J_SUV", "mpv"),
    ("uaz", "Pickup", "LCV", "pickup"),
    ("gaz", "GAZelle Next", "LCV", "mpv"),
    ("gaz", "GAZelle NN", "LCV", "mpv"),
    ("gaz", "Sobol", "LCV", "mpv"),
    ("moskvich", "3", "J_CROSS", "crossover"),
    ("moskvich", "5", "J_CROSS", "crossover"),
    ("moskvich", "6", "D", "sedan"),
    ("moskvich", "8", "J_CROSS", "crossover"),
    ("aurus", "Senat", "F", "sedan"),
    ("aurus", "Komendant", "J_CROSS", "crossover"),
    ("sollers", "Argo", "LCV", "pickup"),
    ("sollers", "ST6", "LCV", "mpv"),
    ("volga", "K30", "D", "sedan"),
    ("volga", "S40", "D", "sedan"),

    # ── mass (Europe + USA, ~70) ────────────────────────────────
    ("renault", "Logan", "B", "sedan"),
    ("renault", "Sandero", "B", "hatchback"),
    ("renault", "Sandero Stepway", "J_CROSS", "hatchback"),
    ("renault", "Duster", "J_CROSS", "crossover"),
    ("renault", "Kaptur", "J_CROSS", "crossover"),
    ("renault", "Arkana", "J_CROSS", "crossover"),
    ("renault", "Megane", "C", "hatchback"),
    ("renault", "Fluence", "C", "sedan"),
    ("renault", "Clio", "B", "hatchback"),
    ("peugeot", "308", "C", "hatchback"),
    ("peugeot", "408", "D", "sedan"),
    ("peugeot", "508", "D", "sedan"),
    ("peugeot", "2008", "J_CROSS", "crossover"),
    ("peugeot", "3008", "J_CROSS", "crossover"),
    ("peugeot", "4008", "J_CROSS", "crossover"),
    ("peugeot", "5008", "J_CROSS", "crossover"),
    ("citroen", "C3", "B", "hatchback"),
    ("citroen", "C4", "C", "hatchback"),
    ("citroen", "C5 Aircross", "J_CROSS", "crossover"),
    ("citroen", "C-Elysee", "B", "sedan"),
    ("citroen", "Berlingo", "M_MPV", "mpv"),
    ("skoda", "Rapid", "B", "sedan"),
    ("skoda", "Octavia", "C", "liftback"),
    ("skoda", "Superb", "D", "liftback"),
    ("skoda", "Karoq", "J_CROSS", "crossover"),
    ("skoda", "Kodiaq", "J_CROSS", "crossover"),
    ("skoda", "Kamiq", "J_CROSS", "crossover"),
    ("skoda", "Yeti", "J_CROSS", "crossover"),
    ("skoda", "Fabia", "B", "hatchback"),
    ("volkswagen", "Polo", "B", "sedan"),
    ("volkswagen", "Golf", "C", "hatchback"),
    ("volkswagen", "Jetta", "C", "sedan"),
    ("volkswagen", "Passat", "D", "sedan"),
    ("volkswagen", "Tiguan", "J_CROSS", "crossover"),
    ("volkswagen", "Touareg", "J_CROSS", "crossover"),
    ("volkswagen", "Teramont", "J_CROSS", "crossover"),
    ("volkswagen", "Multivan", "M_MPV", "mpv"),
    ("volkswagen", "T-Roc", "J_CROSS", "crossover"),
    ("opel", "Astra", "C", "hatchback"),
    ("opel", "Insignia", "D", "sedan"),
    ("opel", "Mokka", "J_CROSS", "crossover"),
    ("opel", "Antara", "J_CROSS", "crossover"),
    ("opel", "Zafira", "M_MPV", "mpv"),
    ("seat", "Leon", "C", "hatchback"),
    ("seat", "Ibiza", "B", "hatchback"),
    ("seat", "Ateca", "J_CROSS", "crossover"),
    ("dacia", "Sandero", "B", "hatchback"),
    ("dacia", "Logan", "B", "sedan"),
    ("dacia", "Duster", "J_CROSS", "crossover"),
    ("fiat", "Punto", "B", "hatchback"),
    ("fiat", "500", "A", "hatchback"),
    ("fiat", "Tipo", "C", "sedan"),
    ("fiat", "Panda", "A", "hatchback"),
    ("ford", "Focus", "C", "hatchback"),
    ("ford", "Mondeo", "D", "sedan"),
    ("ford", "Fiesta", "B", "hatchback"),
    ("ford", "Kuga", "J_CROSS", "crossover"),
    ("ford", "Ecosport", "J_CROSS", "crossover"),
    ("ford", "Explorer", "J_CROSS", "crossover"),
    ("ford", "Edge", "J_CROSS", "crossover"),
    ("ford", "Mustang", "S_SPORT", "coupe"),
    ("chevrolet", "Cruze", "C", "sedan"),
    ("chevrolet", "Aveo", "B", "sedan"),
    ("chevrolet", "Lacetti", "C", "sedan"),
    ("chevrolet", "Niva", "J_SUV", "suv"),
    ("chevrolet", "Captiva", "J_CROSS", "crossover"),
    ("chevrolet", "Tahoe", "J_SUV", "suv"),
    ("chevrolet", "Camaro", "S_SPORT", "coupe"),
    ("dodge", "Charger", "E", "sedan"),
    ("dodge", "Challenger", "S_SPORT", "coupe"),
    ("dodge", "RAM 1500", "LCV", "pickup"),
    ("dodge", "Durango", "J_SUV", "suv"),
    ("chrysler", "300C", "E", "sedan"),
    ("chrysler", "Pacifica", "M_MPV", "mpv"),
    ("jeep", "Wrangler", "J_SUV", "suv"),
    ("jeep", "Cherokee", "J_CROSS", "crossover"),
    ("jeep", "Grand Cherokee", "J_SUV", "suv"),
    ("jeep", "Compass", "J_CROSS", "crossover"),
    ("jeep", "Renegade", "J_CROSS", "crossover"),
    ("mini", "Cooper", "B", "hatchback"),
    ("mini", "Countryman", "J_CROSS", "crossover"),
    ("mini", "Clubman", "B", "wagon"),
    ("smart", "ForTwo", "A", "hatchback"),
    ("smart", "ForFour", "A", "hatchback"),

    # ── japanese_korean_mass (~85) ──────────────────────────────
    ("toyota", "Corolla", "C", "sedan"),
    ("toyota", "Camry", "D", "sedan"),
    ("toyota", "RAV4", "J_CROSS", "crossover"),
    ("toyota", "Land Cruiser", "J_SUV", "suv"),
    ("toyota", "Land Cruiser Prado", "J_SUV", "suv"),
    ("toyota", "Highlander", "J_CROSS", "crossover"),
    ("toyota", "Hilux", "LCV", "pickup"),
    ("toyota", "Fortuner", "J_SUV", "suv"),
    ("toyota", "C-HR", "J_CROSS", "crossover"),
    ("toyota", "Yaris", "B", "hatchback"),
    ("toyota", "Auris", "C", "hatchback"),
    ("toyota", "Avensis", "D", "sedan"),
    ("toyota", "Hiace", "M_MPV", "mpv"),
    ("honda", "Civic", "C", "sedan"),
    ("honda", "Accord", "D", "sedan"),
    ("honda", "CR-V", "J_CROSS", "crossover"),
    ("honda", "HR-V", "J_CROSS", "crossover"),
    ("honda", "Pilot", "J_CROSS", "crossover"),
    ("honda", "Jazz", "B", "hatchback"),
    ("honda", "Odyssey", "M_MPV", "mpv"),
    ("mazda", "3", "C", "sedan"),
    ("mazda", "6", "D", "sedan"),
    ("mazda", "CX-5", "J_CROSS", "crossover"),
    ("mazda", "CX-30", "J_CROSS", "crossover"),
    ("mazda", "CX-9", "J_CROSS", "crossover"),
    ("mazda", "MX-5", "S_SPORT", "cabriolet"),
    ("subaru", "Forester", "J_CROSS", "crossover"),
    ("subaru", "Outback", "J_CROSS", "wagon"),
    ("subaru", "Impreza", "C", "sedan"),
    ("subaru", "XV", "J_CROSS", "crossover"),
    ("subaru", "Legacy", "D", "sedan"),
    ("subaru", "WRX", "S_SPORT", "sedan"),
    ("nissan", "Almera", "B", "sedan"),
    ("nissan", "Qashqai", "J_CROSS", "crossover"),
    ("nissan", "X-Trail", "J_CROSS", "crossover"),
    ("nissan", "Murano", "J_CROSS", "crossover"),
    ("nissan", "Patrol", "J_SUV", "suv"),
    ("nissan", "Pathfinder", "J_CROSS", "crossover"),
    ("nissan", "Terrano", "J_CROSS", "crossover"),
    ("nissan", "Note", "B", "hatchback"),
    ("nissan", "Tiida", "C", "sedan"),
    ("nissan", "Juke", "J_CROSS", "crossover"),
    ("nissan", "GT-R", "S_SPORT", "coupe"),
    ("nissan", "Leaf", "C", "hatchback"),
    ("mitsubishi", "Lancer", "C", "sedan"),
    ("mitsubishi", "Outlander", "J_CROSS", "crossover"),
    ("mitsubishi", "ASX", "J_CROSS", "crossover"),
    ("mitsubishi", "Pajero", "J_SUV", "suv"),
    ("mitsubishi", "Pajero Sport", "J_SUV", "suv"),
    ("mitsubishi", "L200", "LCV", "pickup"),
    ("mitsubishi", "Eclipse Cross", "J_CROSS", "crossover"),
    ("suzuki", "Vitara", "J_CROSS", "crossover"),
    ("suzuki", "SX4", "J_CROSS", "crossover"),
    ("suzuki", "Jimny", "J_SUV", "suv"),
    ("suzuki", "Swift", "B", "hatchback"),
    ("suzuki", "Grand Vitara", "J_SUV", "suv"),
    ("daihatsu", "Terios", "J_CROSS", "crossover"),
    ("isuzu", "D-Max", "LCV", "pickup"),
    ("isuzu", "MU-X", "J_SUV", "suv"),
    ("datsun", "on-DO", "B", "sedan"),
    ("datsun", "mi-DO", "B", "hatchback"),
    ("hyundai", "Solaris", "B", "sedan"),
    ("hyundai", "Accent", "B", "sedan"),
    ("hyundai", "Elantra", "C", "sedan"),
    ("hyundai", "Sonata", "D", "sedan"),
    ("hyundai", "Creta", "J_CROSS", "crossover"),
    ("hyundai", "Tucson", "J_CROSS", "crossover"),
    ("hyundai", "Santa Fe", "J_CROSS", "crossover"),
    ("hyundai", "Palisade", "J_CROSS", "crossover"),
    ("hyundai", "ix35", "J_CROSS", "crossover"),
    ("hyundai", "i30", "C", "hatchback"),
    ("hyundai", "Veloster", "C", "hatchback"),
    ("hyundai", "Staria", "M_MPV", "mpv"),
    ("kia", "Rio", "B", "sedan"),
    ("kia", "Cerato", "C", "sedan"),
    ("kia", "Optima", "D", "sedan"),
    ("kia", "Sportage", "J_CROSS", "crossover"),
    ("kia", "Sorento", "J_CROSS", "crossover"),
    ("kia", "Soul", "B", "hatchback"),
    ("kia", "Picanto", "A", "hatchback"),
    ("kia", "Mohave", "J_SUV", "suv"),
    ("kia", "Stinger", "E", "sedan"),
    ("kia", "Cee'd", "C", "hatchback"),
    ("kia", "Carnival", "M_MPV", "mpv"),
    ("kia", "Seltos", "J_CROSS", "crossover"),
    ("kia", "K5", "D", "sedan"),
    ("ssangyong", "Actyon", "J_CROSS", "crossover"),
    ("ssangyong", "Kyron", "J_SUV", "suv"),
    ("ssangyong", "Rexton", "J_SUV", "suv"),
    ("daewoo", "Nexia", "B", "sedan"),
    ("daewoo", "Matiz", "A", "hatchback"),
    ("daewoo", "Lanos", "B", "sedan"),

    # ── chinese (~90) ───────────────────────────────────────────
    ("geely", "Coolray", "J_CROSS", "crossover"),
    ("geely", "Atlas", "J_CROSS", "crossover"),
    ("geely", "Atlas Pro", "J_CROSS", "crossover"),
    ("geely", "Tugella", "J_CROSS", "crossover"),
    ("geely", "Monjaro", "J_CROSS", "crossover"),
    ("geely", "Emgrand", "C", "sedan"),
    ("geely", "Preface", "D", "sedan"),
    ("geely", "Okavango", "J_CROSS", "crossover"),
    ("geely", "Cityray", "J_CROSS", "crossover"),
    ("chery", "Tiggo 4", "J_CROSS", "crossover"),
    ("chery", "Tiggo 7 Pro", "J_CROSS", "crossover"),
    ("chery", "Tiggo 8 Pro", "J_CROSS", "crossover"),
    ("chery", "Tiggo 8 Pro Max", "J_CROSS", "crossover"),
    ("chery", "Arrizo 8", "D", "sedan"),
    ("chery", "Tiggo 9", "J_CROSS", "crossover"),
    ("haval", "Jolion", "J_CROSS", "crossover"),
    ("haval", "F7", "J_CROSS", "crossover"),
    ("haval", "F7x", "J_CROSS", "crossover"),
    ("haval", "H6", "J_CROSS", "crossover"),
    ("haval", "H9", "J_SUV", "suv"),
    ("haval", "M6", "J_CROSS", "crossover"),
    ("haval", "Dargo", "J_CROSS", "crossover"),
    ("greatwall", "Wingle", "LCV", "pickup"),
    ("greatwall", "Hover", "J_SUV", "suv"),
    ("greatwall", "Poer", "LCV", "pickup"),
    ("changan", "CS35 Plus", "J_CROSS", "crossover"),
    ("changan", "CS55 Plus", "J_CROSS", "crossover"),
    ("changan", "CS75 Plus", "J_CROSS", "crossover"),
    ("changan", "CS95", "J_CROSS", "crossover"),
    ("changan", "UNI-K", "J_CROSS", "crossover"),
    ("changan", "UNI-V", "D", "sedan"),
    ("changan", "Eado", "C", "sedan"),
    ("changan", "Lamore", "B", "sedan"),
    ("exeed", "TXL", "J_CROSS", "crossover"),
    ("exeed", "LX", "J_CROSS", "crossover"),
    ("exeed", "VX", "J_CROSS", "crossover"),
    ("exeed", "RX", "J_CROSS", "crossover"),
    ("exeed", "Pioneer", "J_CROSS", "crossover"),
    ("omoda", "C5", "J_CROSS", "crossover"),
    ("omoda", "S5", "C", "sedan"),
    ("omoda", "7", "J_CROSS", "crossover"),
    ("jaecoo", "J7", "J_CROSS", "crossover"),
    ("jaecoo", "J8", "J_CROSS", "crossover"),
    ("tank", "300", "J_SUV", "suv"),
    ("tank", "500", "J_SUV", "suv"),
    ("tank", "700", "J_SUV", "suv"),
    ("hongqi", "H5", "D", "sedan"),
    ("hongqi", "H9", "F", "sedan"),
    ("hongqi", "HS5", "J_CROSS", "crossover"),
    ("hongqi", "E-HS9", "J_SUV", "suv"),
    ("gac", "GS5", "J_CROSS", "crossover"),
    ("gac", "GS8", "J_CROSS", "crossover"),
    ("gac", "GN8", "M_MPV", "mpv"),
    ("jac", "JS3", "J_CROSS", "crossover"),
    ("jac", "JS4", "J_CROSS", "crossover"),
    ("jac", "JS6", "J_CROSS", "crossover"),
    ("jac", "T6", "LCV", "pickup"),
    ("jac", "T9", "LCV", "pickup"),
    ("baic", "BJ40", "J_SUV", "suv"),
    ("baic", "BJ60", "J_SUV", "suv"),
    ("baic", "BJ80", "J_SUV", "suv"),
    ("baic", "X35", "J_CROSS", "crossover"),
    ("baic", "X55", "J_CROSS", "crossover"),
    ("baic", "X7", "J_CROSS", "crossover"),
    ("baic", "U5 Plus", "C", "sedan"),
    ("byd", "Song Plus", "J_CROSS", "crossover"),
    ("byd", "Han", "E", "sedan"),
    ("byd", "Tang", "J_CROSS", "crossover"),
    ("byd", "Atto 3", "J_CROSS", "crossover"),
    ("byd", "Seal", "D", "sedan"),
    ("byd", "Seagull", "A", "hatchback"),
    ("lifan", "X60", "J_CROSS", "crossover"),
    ("lifan", "Solano", "C", "sedan"),
    ("brilliance", "V5", "J_CROSS", "crossover"),
    ("brilliance", "H230", "B", "sedan"),
    ("dongfeng", "AX7", "J_CROSS", "crossover"),
    ("dongfeng", "580", "J_CROSS", "crossover"),
    ("faw", "Bestune T55", "J_CROSS", "crossover"),
    ("faw", "Bestune T77", "J_CROSS", "crossover"),
    ("faw", "Bestune T99", "J_CROSS", "crossover"),
    ("foton", "Sauvana", "J_SUV", "suv"),
    ("zotye", "T600", "J_CROSS", "crossover"),
    ("aito", "M5", "J_CROSS", "crossover"),
    ("aito", "M7", "J_CROSS", "crossover"),
    ("aito", "M9", "J_CROSS", "crossover"),
    ("lixiang", "L7", "J_CROSS", "crossover"),
    ("lixiang", "L8", "J_CROSS", "crossover"),
    ("lixiang", "L9", "J_CROSS", "crossover"),
    ("lixiang", "ONE", "J_CROSS", "crossover"),
    ("xiaomi", "SU7", "D", "sedan"),
    ("zeekr", "001", "E", "liftback"),
    ("zeekr", "007", "D", "sedan"),
    ("zeekr", "009", "M_MPV", "mpv"),
    ("zeekr", "X", "J_CROSS", "crossover"),
    ("avatr", "11", "J_CROSS", "crossover"),
    ("avatr", "12", "E", "sedan"),
    ("livan", "X3 Pro", "J_CROSS", "crossover"),
    ("livan", "X6 Pro", "J_CROSS", "crossover"),
    ("mhero", "M-HERO 1", "J_SUV", "suv"),
    ("seres", "3", "J_CROSS", "crossover"),
    ("seres", "5", "J_CROSS", "crossover"),
    ("skywell", "ET5", "J_CROSS", "crossover"),
    ("kaiyi", "X3", "J_CROSS", "crossover"),
    ("kaiyi", "X3 Pro", "J_CROSS", "crossover"),
    ("kaiyi", "E5", "C", "sedan"),
    ("voyah", "Free", "J_CROSS", "crossover"),
    ("voyah", "Dream", "M_MPV", "mpv"),
    ("voyah", "Courage", "J_CROSS", "crossover"),
    ("voyah", "Passion", "E", "sedan"),
    ("hiphi", "X", "J_CROSS", "crossover"),
    ("hiphi", "Y", "J_CROSS", "crossover"),
    ("hiphi", "Z", "F", "sedan"),
    ("nio", "ES6", "J_CROSS", "crossover"),
    ("nio", "ES8", "J_CROSS", "crossover"),
    ("nio", "ET7", "E", "sedan"),
    ("wuling", "Hongguang Mini EV", "A", "hatchback"),
    ("mg", "ZS", "J_CROSS", "crossover"),
    ("mg", "HS", "J_CROSS", "crossover"),
    ("mg", "6", "C", "sedan"),
    ("mg", "5", "C", "sedan"),

    # ── premium (~115) ──────────────────────────────────────────
    ("bmw", "1 Series", "C", "hatchback"),
    ("bmw", "2 Series", "C", "coupe"),
    ("bmw", "3 Series", "D", "sedan"),
    ("bmw", "4 Series", "D", "coupe"),
    ("bmw", "5 Series", "E", "sedan"),
    ("bmw", "6 Series", "E", "coupe"),
    ("bmw", "7 Series", "F", "sedan"),
    ("bmw", "8 Series", "F", "coupe"),
    ("bmw", "X1", "J_CROSS", "crossover"),
    ("bmw", "X2", "J_CROSS", "crossover"),
    ("bmw", "X3", "J_CROSS", "crossover"),
    ("bmw", "X4", "J_CROSS", "crossover"),
    ("bmw", "X5", "J_CROSS", "crossover"),
    ("bmw", "X6", "J_CROSS", "crossover"),
    ("bmw", "X7", "J_CROSS", "crossover"),
    ("bmw", "Z4", "S_SPORT", "cabriolet"),
    ("bmw", "M3", "S_SPORT", "sedan"),
    ("bmw", "M5", "S_SPORT", "sedan"),
    ("bmw", "iX", "J_CROSS", "crossover"),
    ("bmw", "i4", "E", "liftback"),
    ("mercedesbenz", "A-Class", "C", "hatchback"),
    ("mercedesbenz", "B-Class", "C", "hatchback"),
    ("mercedesbenz", "C-Class", "D", "sedan"),
    ("mercedesbenz", "E-Class", "E", "sedan"),
    ("mercedesbenz", "S-Class", "F", "sedan"),
    ("mercedesbenz", "CLA", "C", "sedan"),
    ("mercedesbenz", "CLS", "E", "sedan"),
    ("mercedesbenz", "GLA", "J_CROSS", "crossover"),
    ("mercedesbenz", "GLB", "J_CROSS", "crossover"),
    ("mercedesbenz", "GLC", "J_CROSS", "crossover"),
    ("mercedesbenz", "GLE", "J_CROSS", "crossover"),
    ("mercedesbenz", "GLS", "J_CROSS", "crossover"),
    ("mercedesbenz", "G-Class", "J_SUV", "suv"),
    ("mercedesbenz", "V-Class", "M_MPV", "mpv"),
    ("mercedesbenz", "EQS", "F", "sedan"),
    ("mercedesbenz", "AMG GT", "S_SPORT", "coupe"),
    ("audi", "A1", "B", "hatchback"),
    ("audi", "A3", "C", "hatchback"),
    ("audi", "A4", "D", "sedan"),
    ("audi", "A5", "D", "coupe"),
    ("audi", "A6", "E", "sedan"),
    ("audi", "A7", "E", "liftback"),
    ("audi", "A8", "F", "sedan"),
    ("audi", "Q3", "J_CROSS", "crossover"),
    ("audi", "Q5", "J_CROSS", "crossover"),
    ("audi", "Q7", "J_CROSS", "crossover"),
    ("audi", "Q8", "J_CROSS", "crossover"),
    ("audi", "e-tron", "J_CROSS", "crossover"),
    ("audi", "RS6", "S_SPORT", "wagon"),
    ("porsche", "911", "S_SPORT", "coupe"),
    ("porsche", "718 Cayman", "S_SPORT", "coupe"),
    ("porsche", "718 Boxster", "S_SPORT", "cabriolet"),
    ("porsche", "Cayenne", "J_CROSS", "crossover"),
    ("porsche", "Macan", "J_CROSS", "crossover"),
    ("porsche", "Panamera", "F", "liftback"),
    ("porsche", "Taycan", "E", "sedan"),
    ("lexus", "ES", "E", "sedan"),
    ("lexus", "IS", "D", "sedan"),
    ("lexus", "LS", "F", "sedan"),
    ("lexus", "NX", "J_CROSS", "crossover"),
    ("lexus", "RX", "J_CROSS", "crossover"),
    ("lexus", "GX", "J_SUV", "suv"),
    ("lexus", "LX", "J_SUV", "suv"),
    ("lexus", "UX", "J_CROSS", "crossover"),
    ("lexus", "RC", "D", "coupe"),
    ("landrover", "Defender", "J_SUV", "suv"),
    ("landrover", "Discovery", "J_CROSS", "crossover"),
    ("landrover", "Discovery Sport", "J_CROSS", "crossover"),
    ("landrover", "Range Rover", "J_CROSS", "crossover"),
    ("landrover", "Range Rover Sport", "J_CROSS", "crossover"),
    ("landrover", "Range Rover Velar", "J_CROSS", "crossover"),
    ("landrover", "Range Rover Evoque", "J_CROSS", "crossover"),
    ("landrover", "Freelander", "J_CROSS", "crossover"),
    ("cadillac", "Escalade", "J_SUV", "suv"),
    ("cadillac", "XT5", "J_CROSS", "crossover"),
    ("cadillac", "CT6", "F", "sedan"),
    ("volvo", "S60", "D", "sedan"),
    ("volvo", "S90", "E", "sedan"),
    ("volvo", "V60", "D", "wagon"),
    ("volvo", "V90", "E", "wagon"),
    ("volvo", "XC40", "J_CROSS", "crossover"),
    ("volvo", "XC60", "J_CROSS", "crossover"),
    ("volvo", "XC90", "J_CROSS", "crossover"),
    ("infiniti", "QX50", "J_CROSS", "crossover"),
    ("infiniti", "QX60", "J_CROSS", "crossover"),
    ("infiniti", "QX70", "J_CROSS", "crossover"),
    ("infiniti", "QX80", "J_SUV", "suv"),
    ("infiniti", "Q50", "D", "sedan"),
    ("infiniti", "Q70", "E", "sedan"),
    ("jaguar", "F-Pace", "J_CROSS", "crossover"),
    ("jaguar", "E-Pace", "J_CROSS", "crossover"),
    ("jaguar", "I-Pace", "J_CROSS", "crossover"),
    ("jaguar", "XE", "D", "sedan"),
    ("jaguar", "XF", "E", "sedan"),
    ("jaguar", "XJ", "F", "sedan"),
    ("jaguar", "F-Type", "S_SPORT", "coupe"),
    ("genesis", "G70", "D", "sedan"),
    ("genesis", "G80", "E", "sedan"),
    ("genesis", "G90", "F", "sedan"),
    ("genesis", "GV70", "J_CROSS", "crossover"),
    ("genesis", "GV80", "J_CROSS", "crossover"),
    ("genesis", "GV60", "J_CROSS", "crossover"),
    ("tesla", "Model S", "F", "liftback"),
    ("tesla", "Model 3", "D", "sedan"),
    ("tesla", "Model X", "J_CROSS", "crossover"),
    ("tesla", "Model Y", "J_CROSS", "crossover"),
    ("tesla", "Cybertruck", "LCV", "pickup"),
    ("lincoln", "Aviator", "J_CROSS", "crossover"),
    ("lincoln", "Navigator", "J_SUV", "suv"),
    ("lincoln", "Nautilus", "J_CROSS", "crossover"),
    ("lincoln", "Corsair", "J_CROSS", "crossover"),
    ("bentley", "Continental GT", "F", "coupe"),
    ("bentley", "Bentayga", "J_CROSS", "crossover"),
    ("bentley", "Flying Spur", "F", "sedan"),
    ("bentley", "Mulsanne", "F", "sedan"),
    ("rollsroyce", "Phantom", "F", "sedan"),
    ("rollsroyce", "Ghost", "F", "sedan"),
    ("rollsroyce", "Cullinan", "J_SUV", "suv"),
    ("rollsroyce", "Spectre", "F", "coupe"),
    ("rollsroyce", "Wraith", "F", "coupe"),
    ("astonmartin", "DB11", "F", "coupe"),
    ("astonmartin", "Vantage", "S_SPORT", "coupe"),
    ("astonmartin", "DBS", "F", "coupe"),
    ("astonmartin", "DBX", "J_CROSS", "crossover"),
    ("astonmartin", "Rapide", "F", "sedan"),
    ("ferrari", "296 GTB", "S_SPORT", "coupe"),
    ("ferrari", "F8 Tributo", "S_SPORT", "coupe"),
    ("ferrari", "Roma", "S_SPORT", "coupe"),
    ("ferrari", "SF90", "S_SPORT", "coupe"),
    ("ferrari", "Purosangue", "J_CROSS", "crossover"),
    ("ferrari", "812 Superfast", "S_SPORT", "coupe"),
    ("ferrari", "Portofino", "S_SPORT", "cabriolet"),
    ("lamborghini", "Huracan", "S_SPORT", "coupe"),
    ("lamborghini", "Aventador", "S_SPORT", "coupe"),
    ("lamborghini", "Urus", "J_CROSS", "crossover"),
    ("lamborghini", "Revuelto", "S_SPORT", "coupe"),
    ("maserati", "Ghibli", "E", "sedan"),
    ("maserati", "Quattroporte", "F", "sedan"),
    ("maserati", "Levante", "J_CROSS", "crossover"),
    ("maserati", "Grecale", "J_CROSS", "crossover"),
    ("maserati", "MC20", "S_SPORT", "coupe"),
    ("mclaren", "720S", "S_SPORT", "coupe"),
    ("mclaren", "GT", "S_SPORT", "coupe"),
    ("mclaren", "Artura", "S_SPORT", "coupe"),
    ("bugatti", "Chiron", "S_SPORT", "coupe"),
    ("lotus", "Emira", "S_SPORT", "coupe"),
    ("lotus", "Eletre", "J_CROSS", "crossover"),
    ("acura", "TLX", "D", "sedan"),
    ("acura", "MDX", "J_CROSS", "crossover"),
    ("acura", "RDX", "J_CROSS", "crossover"),
    ("alfaromeo", "Giulia", "D", "sedan"),
    ("alfaromeo", "Stelvio", "J_CROSS", "crossover"),
    ("alfaromeo", "Tonale", "J_CROSS", "crossover"),
    ("dsautomobiles", "DS3", "B", "hatchback"),
    ("dsautomobiles", "DS4", "C", "hatchback"),
    ("dsautomobiles", "DS7", "J_CROSS", "crossover"),
]


def _normalize(s: str) -> str:
    return re.sub(r"[^a-z0-9]", "", s.lower())


def main() -> int:
    if not MAKES_CSV.is_file():
        print("FAIL: missing", MAKES_CSV, file=sys.stderr)
        return 1

    make_id_by_norm: dict[str, int] = {}
    with MAKES_CSV.open(encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            make_id_by_norm[row["name_normalized"]] = int(row["id"])

    rows: list[dict[str, str]] = []
    seen_make_model: set[tuple[int, str]] = set()
    for i, (make_norm, name, segment, body) in enumerate(DATA, start=1):
        if make_norm not in make_id_by_norm:
            print(f"FAIL: unknown make {make_norm!r}", file=sys.stderr)
            return 1
        make_id = make_id_by_norm[make_norm]
        norm = _normalize(name)
        key = (make_id, norm)
        if key in seen_make_model:
            print(f"FAIL: duplicate (make_id={make_id}, name={name!r})", file=sys.stderr)
            return 1
        seen_make_model.add(key)
        rows.append({
            "id": str(i),
            "make_id": str(make_id),
            "name": name,
            "name_normalized": norm,
            "segment": segment,
            "body_type": body,
        })

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=["id", "make_id", "name", "name_normalized", "segment", "body_type"],
            lineterminator="\n",
        )
        w.writeheader()
        w.writerows(rows)

    print(f"OK — wrote {len(rows)} rows -> {OUT_CSV.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
